# Generated by Django 2.0.6 on 2018-06-28 03:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testApi',
            new_name='WdjangoApi',
        ),
        migrations.AlterModelTable(
            name='wdjangoapi',
            table='wdjango_api',
        ),
    ]
