# Generated by Django 2.0.6 on 2018-06-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0002_auto_20180628_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScggjyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pubData', models.CharField(max_length=255)),
                ('detailLink', models.CharField(max_length=255)),
                ('detailTitle', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'wdjango_scggjy_list',
            },
        ),
        migrations.RemoveField(
            model_name='wdjangoapi',
            name='owner',
        ),
        migrations.DeleteModel(
            name='WdjangoApi',
        ),
    ]
