# Generated by Django 2.0.6 on 2018-06-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180626_1011'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='wdjango_user',
        ),
    ]
